/**
 * Main thread. Keep this file a list of register() calls.
 * Put feature code in folders. Do not add extra .ts files next to this one.
 *
 * Restart the game after worker.ts or patches.ts changes.
 */
import { isEnabled } from "@modkit/utils";
import { register as registerAction } from "./player/action/register.ts";
import { register as registerAssets } from "./host/assets/register.ts";
import { register as registerAuthorization } from "./factory/authorization/register.ts";
import { register as registerBehaviors } from "./factory/behaviors/register.ts";
import { register as registerBlueprints } from "./factory/blueprints/register.ts";
import { register as registerBuilding } from "./factory/building/register.ts";
import { register as registerBuildings } from "./player/buildings/register.ts";
import { register as registerCamera } from "./player/camera/register.ts";
import { register as registerCollector } from "./factory/collector/register.ts";
import { register as registerCollectorElement } from "./world/collector-element/register.ts";
import { register as registerComponents } from "./ui/components/register.ts";
import { register as registerConservatory } from "./progression/conservatory/register.ts";
import { register as registerConstants } from "./world/constants/register.ts";
import { register as registerCooldown } from "./player/cooldown/register.ts";
import { register as registerDiscoveries } from "./progression/discoveries/register.ts";
import { register as registerEffects } from "./ui/effects/register.ts";
import { register as registerElement } from "./world/element/register.ts";
import { register as registerEnergy } from "./energy/energy/register.ts";
import { register as registerEntities } from "./entities/entities/register.ts";
import { register as registerEvents } from "./world/events/register.ts";
import { register as registerExcavation } from "./world/excavation/register.ts";
import { register as registerFactory } from "./factory/factory/register.ts";
import { register as registerFire } from "./world/fire/register.ts";
import { register as registerGame } from "./host/game/register.ts";
import { register as registerGameConfig } from "./host/game-config/register.ts";
import { register as registerGrid } from "./world/grid/register.ts";
import { register as registerHooks } from "./world/hooks/register.ts";
import { register as registerHotbar } from "./ui/hotbar/register.ts";
import { register as registerI18n } from "./ui/i18n/register.ts";
import { register as registerInput } from "./ui/input/register.ts";
import { register as registerInventory } from "./player/inventory/register.ts";
import { register as registerItems } from "./player/items/register.ts";
import { register as registerLights } from "./ui/lights/register.ts";
import { register as registerManagement } from "./ui/management/register.ts";
import { register as registerMaps } from "./world/maps/register.ts";
import { register as registerMods } from "./host/mods/register.ts";
import { register as registerNavigation } from "./ui/navigation/register.ts";
import { register as registerOverlay } from "./ui/overlay/register.ts";
import { register as registerOverrides } from "./ui/overrides/register.ts";
import { register as registerPatterns } from "./world/patterns/register.ts";
import { register as registerPickups } from "./entities/pickups/register.ts";
import { register as registerPipes } from "./factory/pipes/register.ts";
import { register as registerPlayer } from "./player/player/register.ts";
import { register as registerProcessing } from "./factory/processing/register.ts";
import { register as registerProgression } from "./progression/progression/register.ts";
import { register as registerProjectiles } from "./entities/projectiles/register.ts";
import { register as registerPrompt } from "./ui/prompt/register.ts";
import { register as registerRandom } from "./world/random/register.ts";
import { register as registerRaycast } from "./world/raycast/register.ts";
import { register as registerReaction } from "./world/reaction/register.ts";
import { register as registerRecipes } from "./factory/recipes/register.ts";
import { register as registerRegions } from "./ui/regions/register.ts";
import { register as registerRendering } from "./ui/rendering/register.ts";
import { register as registerResources } from "./energy/resources/register.ts";
import { register as registerRetroGame } from "./ui/retro-game/register.ts";
import { register as registerScene } from "./ui/scene/register.ts";
import { register as registerSchedule } from "./world/schedule/register.ts";
import { register as registerSettings } from "./host/settings/register.ts";
import { register as registerSharedBuffers } from "./host/shared-buffers/register.ts";
import { register as registerSignals } from "./energy/signals/register.ts";
import { register as registerSound } from "./ui/sound/register.ts";
import { register as registerSprites } from "./ui/sprites/register.ts";
import { register as registerStorage } from "./host/storage/register.ts";
import { register as registerStructure } from "./factory/structure/register.ts";
import { register as registerTech } from "./progression/tech/register.ts";
import { register as registerTerrain } from "./world/terrain/register.ts";
import { register as registerTime } from "./host/time/register.ts";
import { register as registerToast } from "./ui/toast/register.ts";
import { register as registerTools } from "./player/tools/register.ts";
import { register as registerTriggers } from "./world/triggers/register.ts";
import { register as registerUpgrades } from "./progression/upgrades/register.ts";
import { register as registerUtils } from "./host/utils/register.ts";
import { register as registerWorkerApi } from "./host/worker-api/register.ts";
import { register as registerWorkers } from "./world/workers/register.ts";

if (isEnabled()) {
  registerElement();
  registerCollectorElement();
  registerTerrain();
  registerReaction();
  registerDiscoveries();
  void registerStructure().then(() => {
    registerBehaviors();
    registerBuildings();
    registerEnergy();
    registerSignals();
    registerConservatory();
  });
  void registerProcessing();
  registerRecipes();
  void registerSprites().then(() => {
    registerProjectiles();
  });
  registerAssets();
  registerEvents();
  registerTriggers();
  registerHooks();
  registerSchedule();
  registerI18n();
  registerStorage();
  registerPrompt();
  registerPlayer();
  registerSettings();
  registerToast();
  registerInput();
  registerManagement();
  registerOverlay();
  registerGrid();
  registerMaps();
  registerExcavation();
  registerFire();
  registerPatterns();
  registerRandom();
  registerRaycast();
  registerConstants();
  registerWorkers();
  registerPipes();
  registerFactory();
  registerAuthorization();
  registerBuilding();
  registerBlueprints();
  registerCollector();
  registerResources();
  registerInventory();
  registerTools();
  registerCamera();
  registerAction();
  registerItems();
  registerCooldown();
  registerRegions();
  registerHotbar();
  registerComponents();
  registerNavigation();
  registerOverrides();
  registerScene();
  registerSound();
  registerEffects();
  registerRendering();
  registerLights();
  registerTech();
  registerUpgrades();
  registerProgression();
  registerEntities();
  registerPickups();
  registerGame();
  registerGameConfig();
  registerMods();
  registerSharedBuffers();
  registerUtils();
  registerTime();
  registerWorkerApi();
  registerRetroGame();
}
