/**
 * Main thread. Keep this file a list of register() calls.
 * Put feature code in the category files. Do not add extra .ts files next to this one.
 *
 * Restart the game after worker.ts or patches.ts changes.
 */
import { isEnabled } from "@modkit/utils";
import { register as registerAction } from "./player/action.ts";
import { register as registerAssets } from "./host/assets.ts";
import { register as registerAuthorization } from "./factory/authorization.ts";
import { register as registerBehaviors } from "./factory/behaviors.ts";
import { register as registerBlueprints } from "./factory/blueprints.ts";
import { register as registerBuilding } from "./factory/building.ts";
import { register as registerBuildings } from "./player/buildings.ts";
import { register as registerCamera } from "./player/camera.ts";
import { register as registerCollector } from "./factory/collector.ts";
import { register as registerCollectorElement } from "./world/collector-element.ts";
import { register as registerComponents } from "./ui/components.ts";
import { register as registerConservatory } from "./progression/conservatory.ts";
import { register as registerConstants } from "./world/constants.ts";
import { register as registerCooldown } from "./player/cooldown.ts";
import { register as registerDiscoveries } from "./progression/discoveries.ts";
import { register as registerEffects } from "./ui/effects.ts";
import { register as registerElement } from "./world/element.ts";
import { register as registerEnergy } from "./energy/energy.ts";
import { register as registerEntities } from "./entities/entities.ts";
import { register as registerEvents } from "./world/events.ts";
import { register as registerExcavation } from "./world/excavation.ts";
import { register as registerFactory } from "./factory/factory.ts";
import { register as registerFire } from "./world/fire.ts";
import { register as registerGame } from "./host/game.ts";
import { register as registerGameConfig } from "./host/game-config.ts";
import { register as registerGrid } from "./world/grid.ts";
import { register as registerHooks } from "./world/hooks.ts";
import { register as registerHotbar } from "./ui/hotbar.ts";
import { register as registerI18n } from "./ui/i18n.ts";
import { register as registerInput } from "./ui/input.ts";
import { register as registerInventory } from "./player/inventory.ts";
import { register as registerItems } from "./player/items.ts";
import { register as registerLights } from "./ui/lights.ts";
import { register as registerManagement } from "./ui/management.ts";
import { register as registerMaps } from "./world/maps.ts";
import { register as registerMods } from "./host/mods.ts";
import { register as registerNavigation } from "./ui/navigation.ts";
import { register as registerOverlay } from "./ui/overlay/register.ts";
import { register as registerOverrides } from "./ui/overrides.ts";
import { register as registerPatterns } from "./world/patterns.ts";
import { register as registerPickups } from "./entities/pickups.ts";
import { register as registerPipes } from "./factory/pipes.ts";
import { register as registerPlayer } from "./player/player.ts";
import { register as registerProcessing } from "./factory/processing.ts";
import { register as registerProgression } from "./progression/progression.ts";
import { register as registerProjectiles } from "./entities/projectiles.ts";
import { register as registerPrompt } from "./ui/prompt.ts";
import { register as registerRandom } from "./world/random.ts";
import { register as registerRaycast } from "./world/raycast.ts";
import { register as registerReaction } from "./world/reaction.ts";
import { register as registerRecipes } from "./factory/recipes.ts";
import { register as registerRegions } from "./ui/regions.ts";
import { register as registerRendering } from "./ui/rendering.ts";
import { register as registerResources } from "./energy/resources.ts";
import { register as registerRetroGame } from "./ui/retro-game.ts";
import { register as registerScene } from "./ui/scene.ts";
import { register as registerSchedule } from "./world/schedule.ts";
import { register as registerSettings } from "./host/settings.ts";
import { register as registerSharedBuffers } from "./host/shared-buffers.ts";
import { register as registerSignals } from "./energy/signals.ts";
import { register as registerSound } from "./ui/sound.ts";
import { register as registerSprites } from "./ui/sprites.ts";
import { register as registerStorage } from "./host/storage.ts";
import { register as registerStructure } from "./factory/structure.ts";
import { register as registerTech } from "./progression/tech.ts";
import { register as registerTerrain } from "./world/terrain.ts";
import { register as registerTime } from "./host/time.ts";
import { register as registerToast } from "./ui/toast.ts";
import { register as registerTools } from "./player/tools.ts";
import { register as registerTriggers } from "./world/triggers.ts";
import { register as registerUpgrades } from "./progression/upgrades.ts";
import { register as registerUtils } from "./host/utils.ts";
import { register as registerWorkerApi } from "./host/worker-api/register.ts";
import { register as registerWorkers } from "./world/workers.ts";

if (isEnabled()) {
  registerElement();
  registerCollectorElement();
  registerTerrain();
  registerReaction();
  registerDiscoveries();
  void registerStructure().then(() => {
    registerBehaviors();
    registerBuildings();
    registerEnergy();
    registerSignals();
    registerConservatory();
  });
  void registerProcessing();
  registerRecipes();
  void registerSprites().then(() => {
    registerProjectiles();
  });
  registerAssets();
  registerEvents();
  registerTriggers();
  registerHooks();
  registerSchedule();
  registerI18n();
  registerStorage();
  registerPrompt();
  registerPlayer();
  registerSettings();
  registerToast();
  registerInput();
  registerManagement();
  registerOverlay();
  registerGrid();
  registerMaps();
  registerExcavation();
  registerFire();
  registerPatterns();
  registerRandom();
  registerRaycast();
  registerConstants();
  registerWorkers();
  registerPipes();
  registerFactory();
  registerAuthorization();
  registerBuilding();
  registerBlueprints();
  registerCollector();
  registerResources();
  registerInventory();
  registerTools();
  registerCamera();
  registerAction();
  registerItems();
  registerCooldown();
  registerRegions();
  registerHotbar();
  registerComponents();
  registerNavigation();
  registerOverrides();
  registerScene();
  registerSound();
  registerEffects();
  registerRendering();
  registerLights();
  registerTech();
  registerUpgrades();
  registerProgression();
  registerEntities();
  registerPickups();
  registerGame();
  registerGameConfig();
  registerMods();
  registerSharedBuffers();
  registerUtils();
  registerTime();
  registerWorkerApi();
  registerRetroGame();
}
